### PR TITLE
docs: add testing for wiki

### PR DESCRIPTION
**Pull request by omermorad**
## Description

This pull request introduces a new document to the InversifyJS repository, focusing on testing strategies with InversifyJS and showcasing the integration of Automock. The document provides a comprehensive guide on two primary approaches to testing: traditional unit and integration testing with InversifyJS, and a streamlined method using Automock. It includes practical examples and code snippets to demonstrate the implementation of these testing strategies.

## Related Issue
N/A

## Motivation and Context
The motivation behind this change is to enhance the InversifyJS documentation by providing clear and practical guidance on effective testing methodologies. This addition addresses the need for comprehensive documentation on integrating InversifyJS with modern testing tools like Automock, thereby aiding developers in writing more efficient and reliable tests.

## How Has This Been Tested?
The added documentation and examples have been reviewed and tested for clarity and accuracy. The examples provided in the document have been executed and verified in a controlled development environment to ensure they accurately demonstrate the intended functionality.

## Types of changes
- [x] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated the changelog.

### CODE REVIEW

**Comment by omermorad** [comment]
Hey @PodaruDragos,

Following up on our conversation in Discord, I've submitted a draft for "Testing" with InversifyJS, coinciding with the upcoming release of the Automock Inversify adapter 🎊 🥳 

I'd appreciate your thoughts on the overall structure and approach. The examples are still a work in progress, but I'm keen to get your feedback on the general direction before finalizing them.

Thanks for your time and input :)

**Comment by PodaruDragos** [comment]
hey @omermorad this looks good to me, thanks for going this.

@notaphplover, @jakehamtexas @Jameskmonger could I please have your opinions on this as well ?

**Comment by omermorad** [comment]
> hey @omermorad this looks good to me, thanks for going this.
> 
> @notaphplover, @jakehamtexas @Jameskmonger could I please have your opinions on this as well ?

Hello, any updates on this? :)

**Review by Jameskmonger — APPROVED** [review]

**Comment by Jameskmonger** [comment]
A really valuable contribution, thank you @omermorad! Apologies for the delay, I am currently recovering from COVID 😷

**Comment by omermorad** [comment]
> A really valuable contribution, thank you @omermorad! Apologies for the delay, I am currently recovering from COVID 😷

Sure, my pleasure 🙏🏻 
And I hope you get over this COVID quickly 💪🏻

**Pull request merged**
