### PR TITLE
Doc: Update get_all_named_tagged.md

### PR DESCRIPTION
**Pull request by Offirmo**
Minor doc update.

### CODE REVIEW

**Comment by lholznagel** [comment]
I hink the `[]` needs to stay there:
`let weapons = kernel.getAll<Weapon[]>("Weapon");  // returns Weapon[]`

**Comment by Offirmo** [comment]
@lholznagel I tested it for real. Using [] cause a typescript failure claiming a return type of Weapon[][]. Not using [] works as expected.

It also makes sense. The [] is redundant and adds nothing.

**Comment by lholznagel** [comment]
Oh okay, thanks for trying :)

**Comment by remojansen** [comment]
Thanks for this as well :)

**Pull request merged**
