### PR TITLE
feat(injectable): allow ignoring duplicate injectable decorators

### PR DESCRIPTION
**Pull request by codeandcats**
Allows ignoring duplicate `injectable` decorators on a class.

## Description
Adds `ignoreDuplicatedInjectableDecorators` function to API to allow ignoring of duplicated injectable decorator calls. Default behaviour is still to throw an error.
e.g.

```typescript
// Entrypoint for application ...
import { ignoreDuplicatedInjectableDecorators } from 'inversify';

ignoreDuplicatedInjectableDecorators(false);
```

## Related Issue
https://github.com/inversify/InversifyJS/issues/563.

## Motivation and Context
I am starting to use Parcel for bundling my TypeScript React app and using its development server which includes hot module reloading. When it reloads module(s) I run into the "Cannot apply @injectable decorator multiple times." error. Other people have reported similar issue with mocha/jest in watch mode.

While this PR keeps the previous behaviour of throwing an error by default, I actually don't fully understand the rationale behind the error in the first place, when we could simply ignore it if its already applied once. As you cannot call the `injectable` decorator with any parameters, each call to it should have exactly the same intention, so ignoring subsequent calls should be fine. I don't think this is a case when we need to fail hard and fast. Notifying the developer to duplicate calls may highlight something odd in their code, but I think the risk is minimal to none since duplicate calls don't really do any harm anyway if we were to just ignore them. If you agree then I can modify this PR to simply remove the error altogether (my preference).

## How Has This Been Tested?
- Used TDD
- Ensured 100% test coverage.
- Tests ran on MacOS 10.14.2 node v8.11.3.
- Also made the changes to the JS in the Inversify module in my node modules for my web app and verified they solve the issue related to HMR in Parcel.

## Types of changes
- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation. - Not sure?
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the changelog.

### CODE REVIEW

**Comment by codeandcats** [comment]
Also...

**Comment by codeandcats** [comment]
Hi @remojansen, I'd love to get this in if possible.

**Comment by codeandcats** [comment]
Hi @remojansen, can this PR go in please? Or better yet, can we just agree to remove the error? I'd be happy to adjust my PR to remove it.

**Comment by codeandcats** [comment]
Hi @Jameskmonger, is there any chance you'd have some time to look at this for me please? I think @remojansen is a little too busy at the mo.

**Comment by codeandcats** [comment]
Closing due to lack of response.

**Comment by sanex3339** [comment]
@remojansen any news about it?

**Comment by veeramarni** [comment]
@remojansen @endel  @mgebundy @ktutnik @tenowg @Jameskmonger @lholznagel @hourliert @jamesadarich @dcavanagh  Any of you please review this PR and get this merged to fix the jest/mocha test cases? I think this error can be ignorable during test cases.

**Pull request closed without merging**
