### PR TITLE
fix typo (`LazyServiceIdentifer` -> `LazyServiceIdentifier`)

### PR DESCRIPTION
**Pull request by unadlib**
## Description

changes interface `LazyServiceIdentifer` name to `LazyServiceIdentifier`

## Types of changes

- [x] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the changelog.

### CODE REVIEW

**Comment by PodaruDragos** [comment]
This look fine to me, we need to consider if this might break for users.

**Comment by unadlib** [comment]
> This look fine to me, we need to consider if this might break for users.

Maybe we can keep the original typo interface for now, also provide the interface with the correct name.

**Comment by Jameskmonger** [comment]
@unadlib I agree, I would propose we keep the renaming (and use the new name internally also) but also export it under an alias of the old name

**Comment by PodaruDragos** [comment]
We could also release a breaking version, which will include other breaking changes that might come, I'm ok either way.
I'll let you guys decide.

**Comment by unadlib** [comment]
> @unadlib I agree, I would propose we keep the renaming (and use the new name internally also) but also export it under an alias of the old name

OK. I have updated it. Please help review.

**Review by Jameskmonger — APPROVED** [review]

**Comment by unadlib** [comment]
hi, @Jameskmonger Can this MR be merged?

**Review by Jameskmonger — APPROVED** [review]

**Comment by Jameskmonger** [comment]
Thank you for the contribution @unadlib, and apologies for the delay in getting this merged.

**Comment by omermorad** [comment]
@Jameskmonger isn't it a breaking change?

**Pull request merged**
