### PR TITLE
Extended tslint rules from tslint:all

### LINKED ISSUE #707: Consider extending from tslint:all or tslint:recommended
`tslint.json` looks like it hasn't been updated since TSLint started shipping with recommended configs. I'd be happy to submit a PR with a stricter ruleset.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
I tried to stick with only whitespace formatting changes for fear of breaking something. A lot of `let`s are now `const`s.

Fixes #707.

### CODE REVIEW

**Comment by lholznagel** [comment]
I restarted the travis job twice, but the error still occurs :/

**Comment by JoshuaKGoldberg** [comment]
Huh, got a clean run locally. Might have done something silly. Will investigate soon.

**Comment by remojansen** [comment]
Hi @JoshuaKGoldberg thanks for this PR I will try to push against your branch this evening. Please leave the PR open and don't delete your branch.

**Comment by remojansen** [comment]
Hi @JoshuaKGoldberg if you merge https://github.com/JoshuaKGoldberg/InversifyJS/pull/1 the build in this PR should go green :smile:

**Comment by lholznagel** [comment]
@remojansen know all builds are red :D

**Comment by remojansen** [comment]
@lholznagel thanks for the heads up, It is not a big deal. Id the performance test that fails sometimes.

**Comment by lholznagel** [comment]
```
/home/travis/build/inversify/InversifyJS/test/container/lookup.test.ts
ERROR: 66:41  no-unused-expression  unused expression, expected an assignment or function call
ERROR: 66:41  whitespace            missing whitespace
ERROR: 66:42  semicolon             Missing semicolon
```

I think that these are linter errors. :)

**Comment by remojansen** [comment]
@lholznagel but you mean in this PR, not in master right? This PR will be fixed once https://github.com/JoshuaKGoldberg/InversifyJS/pull/1 is merged

**Comment by lholznagel** [comment]
Oh okay, I meant the PR, sorry

**Comment by JoshuaKGoldberg** [comment]
Sorry @remojansen can you re-send the PR? Half the builds are passing and I can't figure out why the others aren't 😦

**Comment by remojansen** [comment]
@JoshuaKGoldberg Just created https://github.com/JoshuaKGoldberg/InversifyJS/pull/3 The tests that capture the exceptions for circular dependencies fails sometimes because the exception is not always thrown at the exact same point in the call stack. I have changed the tests to allow two possible valid outcomes.

**Comment by remojansen** [comment]
Hi @JoshuaKGoldberg sorry for the issues I tried to edit the code directly on GitHub and it had some lint issues. Please merge https://github.com/JoshuaKGoldberg/InversifyJS/pull/4 it should be the last one :crossed_fingers:

**Comment by remojansen** [comment]
My mistake again :cry: this should be the final fix https://github.com/JoshuaKGoldberg/InversifyJS/pull/5

**Comment by remojansen** [comment]
:+1: I will review all the changes and merge it later tonight. Thanks a lot for this PR 💯

**Comment by remojansen** [comment]
@JoshuaKGoldberg merged :tada: thanks a lot for your work

**Pull request merged**
