### PR TITLE
Coverage Report

### PR DESCRIPTION
**Pull request by leonardssh**
## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the changelog.

### CODE REVIEW

**Comment by leonardssh** [comment]
Must be found a solution for mocha to generate codecov properly. I'll change this PR in draft until we find it.

**Comment by PodaruDragos** [comment]
this can be easily achieved  if we just port the tests to `jest` as we should.
but I think that is gonna take some time

**Comment by leonardssh** [comment]
That was my idea too, to pass the tests on jest, or even [Vitest](https://vitest.dev/) (still in development), but it looks promising.

**Review by dcavanagh — APPROVED** [review]
LGTM

**Pull request merged**
