### PR TITLE
docs: how to create factory with different scope

### PR DESCRIPTION
**Pull request by Ayzrian**
## Description
Allow to change toFactory scope;
## Related Issue
https://github.com/inversify/InversifyJS/issues/1439

## Motivation and Context

https://github.com/inversify/InversifyJS/issues/1439
## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the changelog.

### CODE REVIEW

**Comment by Ayzrian** [comment]
@LeonardSSH excuse me for bothering you, but any changes you could have a look at it?

**Review by leonardssh — APPROVED** [review]

**Comment by leonardssh** [comment]
Unit Tests fails, take a look.

**Comment by Ayzrian** [comment]
@LeonardSSH I have aligned tests, please have a look

**Comment by Ayzrian** [comment]
Okay the pipelines are green now. Can we merge this PR, or I need to add something else as well?
@LeonardSSH

**Comment by Ayzrian** [comment]
@LeonardSSH  can we merge this, please?

**Comment by Ayzrian** [comment]
@LeonardSSH what do you think if I will change the approach to make it backward compatible? 

I will make `toFactory` return `BindInWhenOnSyntax`, so that by default the scope will be Singleton, while anyone could change scope if needed;

What do you think?

**Comment by PodaruDragos** [comment]
@tonyhallett do you have any objection to this ?

**Comment by Ayzrian** [comment]
@PodaruDragos  I have changed the implementation to be backward compatible; Now `toFactory` returns `InWhenOn` syntax;

**Comment by tonyhallett** [comment]
@PodaruDragos
I am not the best person to ask about Inversify as I have not looked at the source or used it for quite some time now.
What I will say is that the latest commit is much more acceptable than the original.  What is missing from the latest commit is a corresponding change to the interface.

I would also say ( from my vague understanding of Inversiy ) is that any change to toFactory should equally apply to toProvider as it is just an async version of toFactory.

This may be a silly question but is it possible to use toDynamicValue ?

**Comment by Ayzrian** [comment]
@tonyhallett  I am using `toDynamicValue` in my code, to bootstrap a logger each time a function is called, but the problem is that factories are not assembled in `request` scope so the first logger that Azure gave to your code will forever be stuck in the factory, that is incorrect since every call has unique logger from Azure;

So how it looks ;

1. I configure container;
2. When a function is called I create child container and bind logger to `toDynamicValue`.
3. Get an entry point entity, and call business logic;

But the next call factories that are injected in the entities are the same that were in the first call, because `toFactory` is always `Singleton`

Also I have fixed interfaces in b68ff8b

**Comment by Ayzrian** [comment]
@tonyhallett I have did the same changes to `toProvider` in [97cf64e](https://github.com/inversify/InversifyJS/pull/1440/commits/97cf64e760a511946e0796776228c347f7111d55)

**Comment by tonyhallett** [comment]
@Ayzrian
I meant can you use toDynamicValue for your factory.

**Comment by Ayzrian** [comment]
@tonyhallett but this brings a problem that each function will need to pull the factories and the code that these factories envokes and create them in the child container; This can lead to the growing size of the bundle for each azure function and increased boot time, just because one of them is using a factory; 🤔  

Does it make any sense?

**Comment by tonyhallett** [comment]
@Ayzrian 
I only mention it as internally they are treated the same.

https://github.com/inversify/InversifyJS/blob/8f3fd5750078b32b294761a3a365a3bb5218baea/src/resolution/resolver.ts#L85

**Comment by Ayzrian** [comment]
@tonyhallett 

Hmm I got you; I didn't know that `toDynamicValue` receives a `context` as well; In that case `toDynamicValue` can be used as a workaround. Thank you!

IMHO, it would be more convenient and obvious to allow `toFactory` & `toProvider` to have `Request` scope, rather than applying workarounds with `toDynamicValue`

**Comment by tonyhallett** [comment]
> IMHO, it would be more convenient and obvious to allow toFactory & toProvider to have Request scope, rather than applying workarounds with toDynamicValue

As I said, I am not well versed in Inversify as I used to be so I will leave it to @PodaruDragos and @LeonardSSH to decide.  Probably is more than fine to allow opening up the scope but perhaps a change to the documentation will be preferred.  Factory has had this fixed scope for many years, perhaps toDynamicValue is not a workaround but its pupose is to provide a value ( which can be a factory ) using context in the scope that you choose.  

The tyescript typing does suggest that the only way to do a factory is with toFactory.

That's all I have to say on the matteer !

Over to you @PodaruDragos @LeonardSSH

**Comment by Ayzrian** [comment]
Thank you!
So @PodaruDragos , @LeonardSSH , what do you say? Should I update the documentation and we will merge this PR or should we close it?

**Comment by PodaruDragos** [comment]
@Ayzrian I don't see any reason not to merge this, just please update the documentation.

@tonyhallett thanks for the input. I only tagged you since you were planning to update a lot of things with the v6 binding resolution refactor.

**Comment by Ayzrian** [comment]
@PodaruDragos I have updated documentation, please have a look.

**Comment by PodaruDragos** [comment]
cool, thanks. Will merge when the CI is green.

**Pull request merged**
