### PR TITLE
updated and locked all dependencies

### PR DESCRIPTION
**Pull request by lholznagel**
## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] updated dependencies

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lholznagel** [comment]
@remojansen could you restart appveyor?

**Comment by dcavanagh** [comment]
Do we want to lock all the dependencies?

**Comment by lholznagel** [comment]
We had some problems with greenkeeper when not locking the dependencies.

**Comment by remojansen** [comment]
Done by #657

**Pull request closed without merging**
