### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by johnjacobkenny**
Fix inconsistencies and grammar. Let me know if anything looks bad :)

### CODE REVIEW

**Comment by remojansen** [comment]
Thanks for all the PRs 👍

**Comment by johnjacobkenny** [comment]
@remojansen Thank you for the prompt responses and merges! I'm just starting out in contributing to open source and this is keeping me motivated! :)

**Comment by remojansen** [comment]
@kennyjacob that's awesome welcome to the OSS club 👍 If you want I can suggest a few things that I have to do and I think they are not too complex...

Yesterday I released `3.0.0-beta.1` but I haven't update any of the [side-projects](https://github.com/inversify) would you like to help with that? 

You can ignore the devtools because they are not ready. The logger-middleware will be the most complicated one because there are some breaking changes but the rest should be fine.

**Comment by johnjacobkenny** [comment]
@remojansen I'm new to inversify and I wanted to try it out and see how it worked. I am thrilled to be able to contribute, but it will take a while as I get used to how inversify works. If time is not a constraint I can help here and there as I learn. 

If there's something you'd like me to look at specifically (which would be easy to get started with) please let me know. Thanks!

**Comment by remojansen** [comment]
Hi @kennyjacob sorry for the late reply I was away last week... Check out the issues with the `Accepting PRs` tag [here](https://github.com/inversify/InversifyJS/issues?q=is%3Aissue+is%3Aopen+label%3A%22Accepting+PRs%22). 

The first 3 are not too complicated. Please feel free to add comments to the issues if you need hel with them and I will try my best to assist you.

**Pull request merged**
