### PR TITLE
Increase Travis build coverage

### PR DESCRIPTION
**Pull request by Jameskmonger**

### CODE REVIEW

**Comment by Jameskmonger** [comment]
For some reason the environmental variable hasn't been added, @remojansen ... Please try to add it again

**Comment by Jameskmonger** [comment]
This also won't build until the environmental variable is added because GitHub prevents the downloading of TSD typing files @remojansen

**Comment by remojansen** [comment]
I don't think is the token. It seems to be problem with `tslint`

```
UNMET PEER DEPENDENCY tslint@^3 || >=3.1.0-dev || >=3.2.0-dev || >=3.2.1-dev
```

isse_1

The `gulpfile.js` then fails when importing the module:

```
tslint = require("gulp-tslint")
```

isse_2

**Comment by Jameskmonger** [comment]
The npm install is working fine, however `tsd install` is not functioning because it does not have the authentication token.

```
38.70s$ npm install -g tsd
npm WARN engine joi-assert@0.0.3: wanted: {"node":">= 0.10.0 <= 0.11.0"} (current: {"node":"5.4.1","npm":"3.3.12"})
/home/travis/.nvm/versions/node/v5.4.1/bin/tsd -> /home/travis/.nvm/versions/node/v5.4.1/lib/node_modules/tsd/build/cli.js
/home/travis/.nvm/versions/node/v5.4.1/lib
└─┬ tsd@0.6.5 
  ├── assertion-error@1.0.0 
  ├─┬ bl@0.9.5 
  │ └─┬ readable-stream@1.0.33 
  │   ├── core-util-is@1.0.2 
  │   ├── isarray@0.0.1 
  │   └── string_decoder@0.10.31 
  ├── bluebird@1.2.4 
  ├─┬ chalk@1.1.1 
  │ ├── ansi-styles@2.1.0 
  │ ├── escape-string-regexp@1.0.4 
  │ ├─┬ has-ansi@2.0.0 
  │ │ └── ansi-regex@2.0.0 
  │ ├── strip-ansi@3.0.0 
  │ └── supports-color@2.0.0 
  ├── colors@1.1.2 
  ├── deep-freeze@0.0.1 
  ├─┬ definition-header@0.1.0 
  │ ├─┬ parsimmon@0.5.1 
  │ │ └── pjs@5.1.1 
  │ └── xregexp@2.0.0 
  ├─┬ detect-indent@0.2.0 
  │ ├── get-stdin@0.1.0 
  │ └── minimist@0.1.0 
  ├── diff@1.4.0 
  ├─┬ event-stream@3.1.7 
  │ ├── duplexer@0.1.1 
  │ ├── from@0.1.3 
  │ ├── map-stream@0.1.0 
  │ ├── pause-stream@0.0.11 
  │ ├── split@0.2.10 
  │ ├── stream-combiner@0.0.4 
  │ └── through@2.3.8 
  ├── exit@0.1.2 
  ├─┬ glob@4.5.3 
  │ ├─┬ inflight@1.0.4 
  │ │ └── wrappy@1.0.1 
  │ ├── inherits@2.0.1 
  │ ├─┬ minimatch@2.0.10 
  │ │ └─┬ brace-expansion@1.1.2 
  │ │   ├── balanced-match@0.3.0 
  │ │   └── concat-map@0.0.1 
  │ └── once@1.3.3 
  ├─┬ joi@4.9.0 
  │ ├── hoek@2.16.3 
  │ ├── isemail@1.2.0 
  │ ├── moment@2.11.1 
  │ └── topo@1.1.0 
  ├── joi-assert@0.0.3 
  ├── jsesc@0.5.0 
  ├─┬ json-pointer@0.2.2 
  │ └── foreach@2.0.5 
  ├── lazy.js@0.3.2 
  ├── lru-cache@2.5.2 
  ├─┬ minimatch@1.0.0 
  │ └── sigmund@1.0.1 
  ├── minimist@1.2.0 
  ├── ministyle@0.1.4 
  ├─┬ minitable@0.0.4 
  │ └── minichain@0.0.1 
  ├─┬ miniwrite@0.1.4 
  │ └── mkdirp@0.3.5 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── open@0.0.5 
  ├─┬ request@2.67.0 
  │ ├── aws-sign2@0.6.0 
  │ ├─┬ bl@1.0.1 
  │ │ └─┬ readable-stream@2.0.5 
  │ │   ├── process-nextick-args@1.0.6 
  │ │   └── util-deprecate@1.0.2 
  │ ├── caseless@0.11.0 
  │ ├─┬ combined-stream@1.0.5 
  │ │ └── delayed-stream@1.0.0 
  │ ├── extend@3.0.0 
  │ ├── forever-agent@0.6.1 
  │ ├─┬ form-data@1.0.0-rc3 
  │ │ └── async@1.5.2 
  │ ├─┬ har-validator@2.0.6 
  │ │ ├─┬ commander@2.9.0 
  │ │ │ └── graceful-readlink@1.0.1 
  │ │ ├─┬ is-my-json-valid@2.12.4 
  │ │ │ ├── generate-function@2.0.0 
  │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ └── is-property@1.0.2 
  │ │ │ ├── jsonpointer@2.0.0 
  │ │ │ └── xtend@4.0.1 
  │ │ └─┬ pinkie-promise@2.0.0 
  │ │   └── pinkie@2.0.1 
  │ ├─┬ hawk@3.1.3 
  │ │ ├── boom@2.10.1 
  │ │ ├── cryptiles@2.0.5 
  │ │ └── sntp@1.0.9 
  │ ├─┬ http-signature@1.1.0 
  │ │ ├── assert-plus@0.1.5 
  │ │ ├─┬ jsprim@1.2.2 
  │ │ │ ├── extsprintf@1.0.2 
  │ │ │ ├── json-schema@0.2.2 
  │ │ │ └── verror@1.3.6 
  │ │ └─┬ sshpk@1.7.3 
  │ │   ├── asn1@0.2.3 
  │ │   ├── assert-plus@0.2.0 
  │ │   ├─┬ dashdash@1.12.2 
  │ │   │ └── assert-plus@0.2.0 
  │ │   ├── ecc-jsbn@0.1.1 
  │ │   ├── jodid25519@1.0.2 
  │ │   ├── jsbn@0.1.0 
  │ │   └── tweetnacl@0.13.3 
  │ ├── is-typedarray@1.0.0 
  │ ├── isstream@0.1.2 
  │ ├── json-stringify-safe@5.0.1 
  │ ├─┬ mime-types@2.1.9 
  │ │ └── mime-db@1.21.0 
  │ ├── node-uuid@1.4.7 
  │ ├── oauth-sign@0.8.0 
  │ ├── qs@5.2.0 
  │ ├── stringstream@0.0.5 
  │ ├── tough-cookie@2.2.1 
  │ └── tunnel-agent@0.4.2 
  ├── rimraf@2.2.8 
  ├── semver@4.3.6 
  ├── type-detect@0.1.2 
  ├─┬ universal-analytics@0.3.10 
  │ ├── async@0.2.10 
  │ └── underscore@1.8.3 
  ├─┬ update-notifier@0.2.2 
  │ ├─┬ chalk@0.5.1 
  │ │ ├── ansi-styles@1.1.0 
  │ │ ├─┬ has-ansi@0.1.0 
  │ │ │ └── ansi-regex@0.2.1 
  │ │ ├── strip-ansi@0.3.0 
  │ │ └── supports-color@0.2.0 
  │ ├─┬ configstore@0.3.2 
  │ │ ├── graceful-fs@3.0.8 
  │ │ ├─┬ js-yaml@3.5.2 
  │ │ │ ├─┬ argparse@1.0.4 
  │ │ │ │ ├── lodash@4.0.0 
  │ │ │ │ └── sprintf-js@1.0.3 
  │ │ │ └── esprima@2.7.1 
  │ │ ├── object-assign@2.1.1 
  │ │ ├─┬ osenv@0.1.3 
  │ │ │ ├── os-homedir@1.0.1 
  │ │ │ └── os-tmpdir@1.0.1 
  │ │ ├── user-home@1.1.1 
  │ │ └── xdg-basedir@1.0.1 
  │ ├── is-npm@1.0.0 
  │ ├─┬ latest-version@1.0.1 
  │ │ └─┬ package-json@1.2.0 
  │ │   ├─┬ got@3.3.1 
  │ │   │ ├─┬ duplexify@3.4.2 
  │ │   │ │ ├── end-of-stream@1.0.0 
  │ │   │ │ └── readable-stream@2.0.5 
  │ │   │ ├── infinity-agent@2.0.3 
  │ │   │ ├── is-redirect@1.0.0 
  │ │   │ ├── is-stream@1.0.1 
  │ │   │ ├── lowercase-keys@1.0.0 
  │ │   │ ├── nested-error-stacks@1.0.2 
  │ │   │ ├── object-assign@3.0.0 
  │ │   │ ├── prepend-http@1.0.3 
  │ │   │ ├─┬ read-all-stream@3.0.1 
  │ │   │ │ ├─┬ pinkie-promise@1.0.0 
  │ │   │ │ │ └── pinkie@1.0.0 
  │ │   │ │ └── readable-stream@2.0.5 
  │ │   │ └── timed-out@2.0.0 
  │ │   └─┬ registry-url@3.0.3 
  │ │     └─┬ rc@1.1.6 
  │ │       ├── deep-extend@0.4.1 
  │ │       ├── ini@1.3.4 
  │ │       └── strip-json-comments@1.0.4 
  │ ├─┬ semver-diff@2.1.0 
  │ │ └── semver@5.1.0 
  │ └── string-length@1.0.1 
  ├── uri-templates@0.1.9 
  ├── uuid@2.0.1 
  └─┬ verror@1.4.0 
    └── extsprintf@1.0.3 
1.36s$ tsd install
-> running install
[ERR!] GitHub API: GitHub rate limit reached.
    To increase the limit use GitHub authentication.
    See: https://github.com/DefinitelyTyped/tsd#tsdrc
```

**Comment by Jameskmonger** [comment]
Also it is building fine on some of the instances and failing on the others.. I think potentially leave it a bit and rebuild later :stuck_out_tongue:

**Comment by Jameskmonger** [comment]
@remojansen I can confirm that the environment variables are not being set for the TSD auth key. You are the only one who has the permission to set environment variables for the Travis builds so I think you will have to do that.

Travis build issues

**Comment by Jameskmonger** [comment]
Okay @remojansen , the only way to fix this for now was to push my _unencrypted_ OAuth key into the repo. Please remove this from the travis.yml after you merge this pull request!!

**Comment by remojansen** [comment]
I want to research more, it should work because the variable was there:

screen shot 2016-01-23 at 10 46 40

I wonder if this is related:

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code. - [Source](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables)

**Comment by remojansen** [comment]
@Jameskmonger I think I have found how to fix this issue. I will so a pull request shortly :smile: Thanks for your work once more :+1:

**Comment by remojansen** [comment]
@Jameskmonger I think https://github.com/inversify/InversifyJS/pull/50 should fix it :smile: 

Just for reference I followed the guide about [Encrypting Variables Using a Public Key](https://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key)

**Pull request merged**
