### PR TITLE
Use default class property for @optional injected properties

### PR DESCRIPTION
**Pull request by haaijman-imagem**
## Description

Currently the @optional tag overrides class properties defined with typescript-style default values:
```typescript
@injectable()
class Ninja {
    @inject(Weapon) @optional() weapon: Weapon = new Katana();

    ....
}
```
this currently sets the weapon property to `undefined` if no Weapon is present in the container. My proposed change allows does not override the default and results in the weapon property being set to new Katana(). 

(Default values in the constructor already work, but I would prefer not to add boilerplate constructors if this solution is possible.)

## Related Issue
[@optional property injection overrides default](https://github.com/inversify/InversifyJS/issues/1468)

## How Has This Been Tested?
By copying the test case for optional constructor injection but moving the injection to property injection and then running npm test

## Types of changes

- [x] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the changelog.

### CODE REVIEW

**Comment by PodaruDragos** [comment]
LGTM.
can I have your opinion here as well @jakehamtexas ?

**Comment by haaijman-imagem** [comment]
> LGTM. can I have your opinion here as well @jakehamtexas ?

Any updates on this?

**Review by notaphplover — APPROVED** [review]
lgtm!

**Comment by notaphplover** [comment]
@haaijman-imagem can you update the branch? After that I would say we can merge it

**Review by Jameskmonger — APPROVED** [review]

**Pull request merged**
