### PR TITLE
Allow to use symbols or numbers as names and tags

### PR DESCRIPTION
**Pull request by sanex3339**
It would be nice to use `numbers` and `symbols` as name and tag values in `whenTargetNamed` , `whenTargetTagged` and other methods and corresponding annotations'

https://github.com/inversify/InversifyJS/issues/425

```javascript
enum NodeTransformers {
    CatchClauseObfuscator,
    FunctionDeclarationObfuscator,
    FunctionObfuscator
}

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(CatchClauseObfuscator)
    .whenTargetNamed(NodeTransformers.CatchClauseObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionDeclarationObfuscator)
    .whenTargetNamed(NodeTransformers.FunctionDeclarationObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionObfuscator)
    .whenTargetNamed(NodeTransformers.FunctionObfuscator);
```

Same with `whenTargetTagged`. It would be nice to use as tag `numbers` or `symbols`:
```javascript
const tag: symbol = Symbol();

enum NodeTransformers {
    CatchClauseObfuscator,
    FunctionDeclarationObfuscator,
    FunctionObfuscator
}

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(CatchClauseObfuscator)
    .whenTargetTagged(tag, NodeTransformers.CatchClauseObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionDeclarationObfuscator)
    .whenTargetTagged(tag, NodeTransformers.FunctionDeclarationObfuscator);

bind<INodeTransformer>(ServiceIdentifiers.INodeTransformer)
    .to(FunctionObfuscator)
    .whenTargetTagged(tag, NodeTransformers.FunctionObfuscator);
```

### CODE REVIEW

**Comment by remojansen** [comment]
@sanex3339 thanks for the PR take your time to fix it. If you are busy don't worry leave it open. And I will send a PR to your PR.

**Comment by sanex3339** [comment]
Hmm. Strange behaviour with `Symbol('blablabla').toString()`. 
https://ci.appveyor.com/project/remojansen/inversifyjs/build/282/job/l5lqfu0fgkj11u6c#L1667

`@@blablabla` result in IE11 and PhantomJS doesn't look like a standard behaviour for `Symbol`.
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toString

**Comment by remojansen** [comment]
I have sent you a PR that I hope will fix the build 😄

**Comment by remojansen** [comment]
Thanks for merging my PR. The AppVeyor build failed due to a timeout. It is re-building now ⏳

**Comment by remojansen** [comment]
Merged 🎉

**Pull request merged**
