### PR TITLE
fix error when using LazyServiceIdentifer propetrty injection

### LINKED ISSUE #865: Can't implement circular dependencies
I need to implement circular dependency. But workarounds in docs don't work for me.
I used lazyServiceIdentifie LazyServiceIdentifer, lazyInject but there some errors.

For example:

A injects B, B injects A. 

## Expected Behavior
A injected in B. B injected in A.

## Current Behavior
I got error when use lazyInject
```
TypeError: Cannot read property 'get' of undefined
    at resolve (webpack-internal:///./node_modules/inversify-inject-decorators/lib/decorators.js:30:34)
    at AppStore.getter [as http] (webpack-internal:///./node_modules/inversify-inject-decorators/lib/decorators.js:7:47)
	at AppStore.remoteFunction (<anonymous>:2:14)
```

## Steps to Reproduce (for bugs)

1. Create two classes marked  @injectable 
2. Create decorators with getDecorators from inversify-inject-decorators
3. Use @lazyInject to inject them to each other

## Context

I try configure us common service, but to do it i need to use some methods from another service. 
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

# Stack trace

### LINKED ISSUE #944: LazyServiceIdentifer does not work for property injection
Unable to lazily inject circular service dependency via _property_ injection. 

Side-note: Identifer -> Identifier

## Expected Behavior
Inject without error

## Current Behavior
throws error

## Steps to Reproduce (for bugs)

```ts
import "reflect-metadata";
import { Container, injectable, inject, LazyServiceIdentifer } from "inversify";

const container = new Container();

interface IModuleA {}
interface IModuleB {}

const moduleA = Symbol.for("IModuleA");
const moduleB = Symbol.for("IModuleB");

@injectable()
class ModuleA implements IModuleA {
  @inject(new LazyServiceIdentifer(()=>moduleB))
  b: IModuleB;
}

@injectable()
class ModuleB implements IModuleB{
  @inject(new LazyServiceIdentifer(()=>moduleA))
  a: IModuleA
}

container.bind(moduleA).to(ModuleA).inSingletonScope();
container.bind(moduleB).to(ModuleB).inSingletonScope();

let bar = container.get(moduleA);

console.log(bar);
```

## Context

I'm aware that injecting via the constructor works; however in NInject I was able to do this kind of lazy property injection within a base "Module" class. Subsequent derivations of that "Module" class then didn't have to deal with adding those dependencies manually. 

## Environment
inversify: "^4.13.0"
node-js: 10.1.0

# Stack trace
```
Error: No matching bindings found for serviceIdentifier: [object Object]
    at _validateActiveBindingCount (D:\Code\logger\node_modules\inversify\lib\planning\planner.js:62:23)
    at _getActiveBindings (D:\Code\logger\node_modules\inversify\lib\planning\planner.js:48:5)
    at _createSubRequests (D:\Code\logger\node_modules\inversify\lib\planning\planner.js:91:26)
    at D:\Code\logger\node_modules\inversify\lib\planning\planner.js:115:17
    at Array.forEach (<anonymous>)
    at D:\Code\logger\node_modules\inversify\lib\planning\planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (D:\Code\logger\node_modules\inversify\lib\planning\planner.js:94:20)
    at Object.plan (D:\Code\logger\node_modules\inversify\lib\planning\planner.js:136:9)
    at D:\Code\logger\node_modules\inversify\lib\container\container.js:318:37
```

### PR DESCRIPTION
**Pull request by csr632**
## Description
LazyServiceIdentifer where added at https://github.com/inversify/InversifyJS/pull/774 . But the PR only supported LazyServiceIdentifer in contruction injection and forgot to consider property injection. 

## Related Issue

fix https://github.com/inversify/InversifyJS/issues/944
fix https://github.com/inversify/InversifyJS/issues/865

## Types of changes

- [x] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the changelog.

### CODE REVIEW

**Comment by csr632** [comment]
@dcavanagh Could you please take a look at this?

**Comment by Israfil22** [comment]
Wtf, 2 years to merge a little solution to a big problem?

**Comment by jkhmtx** [comment]
This change appears to have been incorporated in https://github.com/inversify/InversifyJS/commit/f9b8fb59e732b09da56f5e5cf227222ebe71fff3#diff-017dc969fe787636170ee464d6b4bbb92a2fb3cb55ccae660ac36a7db092d2efR89

cc: @Israfil22

**Comment by sraka1** [comment]
@jakehamtexas that is not the same change. That commit fixed the issue for getConstructorArgsAsTarget, this PR fixes it for getClassPropsAsTargets. Can you please reopen this issue?

**Pull request closed without merging**
